#pragma once

#include <QWidget>

// Why is class Settings inside namespace Ui?
// This is a Qt-specific convention used to separate the logic of your class
// from the visual layout generated by the Qt Designer.

// The Generated UI Class:
// When you design a .ui file, the Qt User Interface Compiler (uic) generates a C++ class
// to represent those buttons and sliders. To avoid naming conflicts with your actual logic class,
// it wraps the generated one in the Ui namespace.

// Logic Class:
// Your Settings class (the one inheriting from QWidget) is in the global namespace.
// It has a pointer member: Ui::Settings *ui;.

// This allows you to have a class named Settings that contains a helper object
// also named Settings, without the compiler getting confused.

// Qt UI Namespace
namespace Ui {
	class Settings;
}

// Forward Declaration
// Reduces compile times and avoids circular includes.
class MainWindow;

class Settings : public QWidget {
	Q_OBJECT

public:
	explicit Settings(QWidget *parent = nullptr);
	~Settings();

private slots:
	void onStyleChanged(const QString &name);
	void onTestModeToggled(bool checked);
	void onMenuPageChanged(int index);
	void loadLogFile();
	void openLogLocation();
	void clearLogFile();

private:
	Ui::Settings *ui;
	MainWindow *m_previewWindow = nullptr;

	void updatePreview();
	void applyDarkFusion();
	bool isSystemDark();
	void saveSettings();
};