#include "Settings.h"
#include "Config.h"
#include "LogHelper.h"
#include "MainWindow.h"
#include "ui_Settings.h" // Header generated by uic from Settings.ui

// Settings::Settings(QWidget *parent) - Definition of the Settings constructor:
// the parameter parent is a pointer to the widget that will own this dialog
// (default nullptr).

// QDialog(parent) - Base‑class initializer:
// before the body runs, the QDialog part of the object is constructed,
// passing parent to QDialog’s constructor. This sets the dialog’s
// parent/ownership and initializes all QDialog internals.

// ui(new Ui::Settings) - Member initializer:
// creates a new instance of the UI helper class and stores its address in the
// member ui. Using the initializer list is required for
// non‑default‑constructible members (here we need to allocate the object on the
// heap).

// Why use an initializer list?
// Efficiency – members are constructed directly with the given arguments;
// otherwise they would be default‑constructed first and then assigned.
Settings::Settings(QWidget *parent)
	: QWidget(parent), // Call the base‑class (QWidget) constructor
	  ui(new Ui::Settings) // Initialise the member pointer `ui`
{
	ui->setupUi(this); // Populate the dialog with the widgets from the .ui file

	// Load values from Config
	ui->checkLogHistory->setChecked(Config::LOG_HISTORY_ENABLED);
	ui->checkChecksum->setChecked(Config::CHECKSUM_ENABLED);
	ui->checkCloseOnFinish->setChecked(Config::CLOSE_ON_FINISH);
	ui->checkTimeLabels->setChecked(Config::SPEED_GRAPH_SHOW_TIME_LABELS);
	ui->checkAlignRight->setChecked(Config::SPEED_GRAPH_ALIGN_LABELS_RIGHT);
	ui->spinHistorySize->setValue(Config::SPEED_GRAPH_HISTORY_SIZE_USER);
	ui->spinMaxSpeed->setValue(Config::SPEED_GRAPH_MAX_SPEED);

	// Menu Navigation
	connect(ui->listWidgetMenu, &QListWidget::currentRowChanged, ui->stackedWidget, &QStackedWidget::setCurrentIndex);
	ui->listWidgetMenu->setCurrentRow(0); // Default to General

	// About Page
	ui->lblAppName->setText(QString("<b>%1</b>").arg(APP_NAME));
	ui->lblAppName->setStyleSheet("font-size: 18pt;");
	ui->lblVersion->setText(QString("Version %1").arg(APP_VERSION));
	ui->lblDeveloper->setText(QString("Developed by %1").arg(Config::DEVELOPER));
	ui->lblWebsite->setText(QString("<a href=\"%1\">%1</a>").arg(Config::WEBSITE_URL));
	ui->lblWebsite->setOpenExternalLinks(true);
	connect(ui->btnAboutQt, &QPushButton::clicked, qApp, &QApplication::aboutQt);

	connect(ui->checkTestMode, &QCheckBox::toggled, this, &Settings::onTestModeToggled);
	connect(ui->checkAlignRight, &QCheckBox::toggled, this, &Settings::updatePreview);
	connect(ui->checkTimeLabels, &QCheckBox::toggled, this, &Settings::updatePreview);
	connect(ui->spinMaxSpeed, &QDoubleSpinBox::valueChanged, this, &Settings::updatePreview);

	connect(ui->btnOK, &QPushButton::clicked, this, [this]() {
		// Save values to Config
		Config::LOG_HISTORY_ENABLED = ui->checkLogHistory->isChecked();
		Config::CHECKSUM_ENABLED = ui->checkChecksum->isChecked();
		Config::CLOSE_ON_FINISH = ui->checkCloseOnFinish->isChecked();
		Config::SPEED_GRAPH_SHOW_TIME_LABELS = ui->checkTimeLabels->isChecked();
		Config::SPEED_GRAPH_ALIGN_LABELS_RIGHT = ui->checkAlignRight->isChecked();
		Config::SPEED_GRAPH_HISTORY_SIZE_USER = ui->spinHistorySize->value();
		Config::SPEED_GRAPH_HISTORY_SIZE = Config::SPEED_GRAPH_HISTORY_SIZE_USER;
		Config::SPEED_GRAPH_MAX_SPEED = ui->spinMaxSpeed->value();

		Config::save();
		close();
	});

	connect(ui->btnCancel, &QPushButton::clicked, this, &QWidget::close);
}

Settings::~Settings() {
	if (m_previewWindow) {
		m_previewWindow->close();
		delete m_previewWindow;
	}
	delete ui;
}

void Settings::onTestModeToggled(bool checked) {
	if (checked) {
		if (!m_previewWindow) {
			std::vector<std::string> dummySrc = {""};

			// Passing nullptr here ensures the Preview isn't "blocked" by the Settings parent
			m_previewWindow = new MainWindow(OperationMode::PreviewUI, dummySrc, "", nullptr);
			m_previewWindow->setAttribute(Qt::WA_DeleteOnClose);

			connect(m_previewWindow, &QWidget::destroyed, this, [this]() {
				m_previewWindow = nullptr;
				// Block signals so we don't re-trigger this function recursively
				ui->checkTestMode->blockSignals(true);
				ui->checkTestMode->setChecked(false);
				ui->checkTestMode->blockSignals(false);
			});

			// Positioning Logic
			QRect settingsRect = this->frameGeometry();
			int margin = 10;

			// Move to the left of Settings
			int x = settingsRect.left() - m_previewWindow->frameGeometry().width() - margin;
			int y = settingsRect.top();
			m_previewWindow->move(x, y);

			m_previewWindow->show();
		}
	} else {
		if (m_previewWindow) {
			// No need to call delete here if you use WA_DeleteOnClose;
			// close() will trigger the deletion.
			m_previewWindow->close();
			m_previewWindow = nullptr;
		}
	}
}

void Settings::updatePreview() {
	Config::SPEED_GRAPH_ALIGN_LABELS_RIGHT = ui->checkAlignRight->isChecked();
	Config::SPEED_GRAPH_SHOW_TIME_LABELS = ui->checkTimeLabels->isChecked();
	Config::SPEED_GRAPH_MAX_SPEED = ui->spinMaxSpeed->value();
}