#include <QStyleFactory>
#include <QProcess>

#include "Config.h"
#include "MainWindow.h"
#include "Settings.h"
#include "ui_Settings.h" // Header generated by uic from Settings.ui
#include <QLibraryInfo>
#include <QTranslator>

// Settings::Settings(QWidget *parent) - Definition of the Settings constructor:
// the parameter parent is a pointer to the widget that will own this dialog
// (default nullptr).

// QDialog(parent) - Base‑class initializer:
// before the body runs, the QDialog part of the object is constructed,
// passing parent to QDialog’s constructor. This sets the dialog’s
// parent/ownership and initializes all QDialog internals.

// ui(new Ui::Settings) - Member initializer:
// creates a new instance of the UI helper class and stores its address in the
// member ui. Using the initializer list is required for
// non‑default‑constructible members (here we need to allocate the object on the
// heap).

// Why use an initializer list?
// Efficiency – members are constructed directly with the given arguments;
// otherwise they would be default‑constructed first and then assigned.
Settings::Settings(QWidget *parent)
	: QWidget(parent), // Call the base‑class (QWidget) constructor
	  ui(new Ui::Settings) // Initialise the member pointer `ui`
{
	ui->setupUi(this); // Populate the dialog with the widgets from the .ui file

	// Load values from Config
	ui->checkLogHistory->setChecked(Config::LOG_HISTORY_ENABLED);
	ui->checkChecksum->setChecked(Config::CHECKSUM_ENABLED);
	ui->checkCloseOnFinish->setChecked(Config::CLOSE_ON_FINISH);
	ui->checkTimeLabels->setChecked(Config::SPEED_GRAPH_SHOW_TIME_LABELS);
	ui->checkAlignRight->setChecked(Config::SPEED_GRAPH_ALIGN_LABELS_RIGHT);
	ui->spinHistorySize->setValue(Config::SPEED_GRAPH_HISTORY_SIZE_USER);
	ui->spinMaxSpeed->setValue(Config::SPEED_GRAPH_MAX_SPEED);

	// Menu Navigation
	connect(ui->listWidgetMenu, &QListWidget::currentRowChanged, ui->stackedWidget, &QStackedWidget::setCurrentIndex);
	ui->listWidgetMenu->setCurrentRow(0); // Default to General

	// General page
	ui->comboLanguage->addItem("English", "en");
	ui->comboLanguage->addItem("Romanian", "ro");
	int langIdx = ui->comboLanguage->findData(Config::LANGUAGE);
	if (langIdx != -1)
		ui->comboLanguage->setCurrentIndex(langIdx);

	ui->comboStyle->addItems(QStyleFactory::keys());
	ui->comboStyle->addItem("Fusion Dark");
	connect(ui->comboStyle, &QComboBox::currentTextChanged, this, &Settings::onStyleChanged);

	// Set saved style
	ui->comboStyle->setCurrentText(Config::UI_STYLE);

	// Find the current style and set it as the active item
	if (Config::UI_STYLE.isEmpty()) {
		ui->comboStyle->setCurrentText(qApp->style()->objectName());
		// QString defaultStyle = isSystemDark() ? "Fusion Dark" : "Fusion";
		// ui->comboStyle->setCurrentText(defaultStyle);
	}

	// Restart warning logic
	ui->lblRestartWarning->setVisible(false);
	ui->btnRestart->setVisible(false);

	connect(ui->comboLanguage, &QComboBox::currentIndexChanged, this, [this]() {
		bool changed = (ui->comboLanguage->currentData().toString() != Config::LANGUAGE);
		ui->lblRestartWarning->setVisible(changed);
		ui->btnRestart->setVisible(changed);
	});

	connect(ui->btnRestart, &QPushButton::clicked, this, [this]() {
		saveSettings(); 
		
		// Get existing arguments (excluding the app path itself)
		QStringList args = QCoreApplication::arguments();
		if (!args.isEmpty()) {
			args.removeFirst(); 
		}

		// Start the new instance
		// Passing applicationFilePath() and the filtered args list
		if (QProcess::startDetached(QCoreApplication::applicationFilePath(), args)) {
			// Only quit if the new process successfully launched
			qApp->quit();
		} else {
			qWarning() << "Failed to restart the application.";
		}
	});

	// About Page
	ui->lblAppName->setText(QString("<b>%1</b>").arg(APP_NAME));
	ui->lblAppName->setStyleSheet("font-size: 18pt;");
	ui->lblVersion->setText(QString("Version %1").arg(APP_VERSION));
	ui->lblDescription->setText(QCoreApplication::translate("Settings", Constants::DESCRIPTION));
	ui->lblDeveloper->setText(QString("<span>%1 &#169; 2026</span>").arg(Config::DEVELOPER));
	ui->lblWebsite->setText(QString("<a href=\"%1\">%1</a>").arg(Constants::WEBSITE_URL));
	ui->lblWebsite->setOpenExternalLinks(true);
	ui->lblGithub->setText(QString("<a href=\"%1\">%1</a>").arg(Constants::GITHUB_URL));
	ui->lblGithub->setOpenExternalLinks(true);
	QString html = R"(<a href="%1"><img src="%2" alt="Buy Me A Coffee" height="60" width="200"></a>)";
	ui->lblDonate->setText(html.arg(Constants::DONATE_URL, Constants::DONATE_IMG));
	ui->lblDonate->setOpenExternalLinks(true);

	connect(ui->btnAboutQt, &QPushButton::clicked, qApp, &QApplication::aboutQt);
	connect(ui->checkTestMode, &QCheckBox::toggled, this, &Settings::onTestModeToggled);
	connect(ui->checkAlignRight, &QCheckBox::toggled, this, &Settings::updatePreview);
	connect(ui->checkTimeLabels, &QCheckBox::toggled, this, &Settings::updatePreview);
	connect(ui->spinMaxSpeed, &QDoubleSpinBox::valueChanged, this, &Settings::updatePreview);

	connect(ui->btnDefaults, &QPushButton::clicked, this, [this]() {
		ui->checkLogHistory->setChecked(Config::Defaults::LOG_HISTORY_ENABLED);
		ui->checkChecksum->setChecked(Config::Defaults::CHECKSUM_ENABLED);
		ui->checkCloseOnFinish->setChecked(Config::Defaults::CLOSE_ON_FINISH);
		ui->checkTimeLabels->setChecked(Config::Defaults::SPEED_GRAPH_SHOW_TIME_LABELS);
		ui->checkAlignRight->setChecked(Config::Defaults::SPEED_GRAPH_ALIGN_LABELS_RIGHT);
		ui->spinHistorySize->setValue(Config::Defaults::SPEED_GRAPH_HISTORY_SIZE_USER);
		ui->spinMaxSpeed->setValue(Config::Defaults::SPEED_GRAPH_MAX_SPEED);

		QString defLang = Config::Defaults::LANGUAGE;
		int defLangIdx = ui->comboLanguage->findData(defLang);
		if (defLangIdx != -1)
			ui->comboLanguage->setCurrentIndex(defLangIdx);

		QString defStyle = Config::Defaults::UI_STYLE;
		if (defStyle.isEmpty()) {
			int idx = ui->comboStyle->findText("Fusion");
			if (idx != -1)
				ui->comboStyle->setCurrentIndex(idx);
		} else {
			ui->comboStyle->setCurrentText(defStyle);
		}
	});

	connect(ui->btnOK, &QPushButton::clicked, this, [this]() {
		saveSettings();
		close();
	});

	connect(ui->btnCancel, &QPushButton::clicked, this, &QWidget::close);
}

Settings::~Settings() {
	if (m_previewWindow) {
		m_previewWindow->close();
		delete m_previewWindow;
	}
	delete ui;
}

void Settings::onTestModeToggled(bool checked) {
	if (checked) {
		if (!m_previewWindow) {
			std::vector<std::string> dummySrc = {""};

			// Passing nullptr here ensures the Preview isn't "blocked" by the Settings parent
			m_previewWindow = new MainWindow(OperationMode::PreviewUI, dummySrc, "", nullptr);
			m_previewWindow->setAttribute(Qt::WA_DeleteOnClose);

			connect(m_previewWindow, &QWidget::destroyed, this, [this]() {
				m_previewWindow = nullptr;
				// Block signals so we don't re-trigger this function recursively
				ui->checkTestMode->blockSignals(true);
				ui->checkTestMode->setChecked(false);
				ui->checkTestMode->blockSignals(false);
			});

			// Positioning Logic
			QRect settingsRect = this->frameGeometry();
			int margin = 10;

			// Move to the left of Settings
			int x = settingsRect.left() - m_previewWindow->frameGeometry().width() - margin;
			int y = settingsRect.top();
			m_previewWindow->move(x, y);

			m_previewWindow->show();
		}
	} else {
		if (m_previewWindow) {
			// No need to call delete here if you use WA_DeleteOnClose;
			// close() will trigger the deletion.
			m_previewWindow->close();
			m_previewWindow = nullptr;
		}
	}
}


void Settings::onStyleChanged(const QString &name) {
	// Temporarily remove stylesheet to prevent "ghost" colors during the transition
	QString oldSheet = qApp->styleSheet();
	qApp->setStyleSheet("");

	if (name == "Fusion Dark") {
		// Fusion doesn't have a native dark mode, so we apply the engine + our palette
		QApplication::setStyle(QStyleFactory::create("Fusion"));
		applyDarkFusion();
	} else {
		// For all other styles (Adwaita-Dark, Breeze, etc.),
		// let the Style Engine handle the palette entirely.
		QApplication::setStyle(QStyleFactory::create(name));

		// Tell the app to use the palette
		// provided by the newly selected native style.
		qApp->setPalette(QApplication::style()->standardPalette());
	}

	// Re-apply our custom QSS rules
	qApp->setStyleSheet(oldSheet);

	// Save style
	Config::UI_STYLE = ui->comboStyle->currentText();
}


void Settings::updatePreview() {
	Config::SPEED_GRAPH_ALIGN_LABELS_RIGHT = ui->checkAlignRight->isChecked();
	Config::SPEED_GRAPH_SHOW_TIME_LABELS = ui->checkTimeLabels->isChecked();
	Config::SPEED_GRAPH_MAX_SPEED = ui->spinMaxSpeed->value();
}


void Settings::applyDarkFusion() {
	QPalette darkPalette;
	darkPalette.setColor(QPalette::Window, QColor(53, 53, 53));
	darkPalette.setColor(QPalette::WindowText, Qt::white);
	darkPalette.setColor(QPalette::Base, QColor(25, 25, 25));
	darkPalette.setColor(QPalette::AlternateBase, QColor(53, 53, 53));
	darkPalette.setColor(QPalette::Text, Qt::white);
	darkPalette.setColor(QPalette::Button, QColor(53, 53, 53));
	darkPalette.setColor(QPalette::ButtonText, Qt::white);
	darkPalette.setColor(QPalette::BrightText, Qt::red);
	darkPalette.setColor(QPalette::Link, QColor(42, 130, 218));
	darkPalette.setColor(QPalette::Highlight, QColor(42, 130, 218));
	darkPalette.setColor(QPalette::HighlightedText, Qt::black);
	darkPalette.setColor(QPalette::ToolTipBase, QColor(53, 53, 53)); // Dark background
	darkPalette.setColor(QPalette::ToolTipText, Qt::white); // White text

	qApp->setPalette(darkPalette);
}


bool Settings::isSystemDark() {
	QPalette defaultPalette = qApp->palette();
	// Check if the window background is darker than the text
	return defaultPalette.color(QPalette::WindowText).lightness() >
		defaultPalette.color(QPalette::Window).lightness();
}

void Settings::saveSettings() {
	Config::LOG_HISTORY_ENABLED = ui->checkLogHistory->isChecked();
	Config::CHECKSUM_ENABLED = ui->checkChecksum->isChecked();
	Config::CLOSE_ON_FINISH = ui->checkCloseOnFinish->isChecked();
	Config::SPEED_GRAPH_SHOW_TIME_LABELS = ui->checkTimeLabels->isChecked();
	Config::SPEED_GRAPH_ALIGN_LABELS_RIGHT = ui->checkAlignRight->isChecked();
	Config::SPEED_GRAPH_HISTORY_SIZE_USER = ui->spinHistorySize->value();
	Config::SPEED_GRAPH_HISTORY_SIZE = Config::SPEED_GRAPH_HISTORY_SIZE_USER;
	Config::SPEED_GRAPH_MAX_SPEED = ui->spinMaxSpeed->value();
	Config::LANGUAGE = ui->comboLanguage->currentData().toString();

	Config::save();
}
